name: Test
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.13"
          - "3.12"
          - "3.11"
          - "3.10"
          - "3.9"
          - "3.8"
      fail-fast: false
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - uses: actions/checkout@v5
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
          allow-prereleases: true
      - uses: astral-sh/setup-uv@v6
      - name: Install dependencies
        run: uv sync --all-extras --all-groups
      - name: Test
        run: uv run python tests/runtests.py
      - name: Build
        run: uv build

  test_py37:
    runs-on: ubuntu-latest
    container: python:3.7-slim
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
      - uses: astral-sh/setup-uv@v6
      - name: Install dependencies
        run: uv sync --all-extras --all-groups --python=python3.7
      - name: Test
        run: |
          uv run python tests/runtests.py
          uv run python -V
      - name: Build
        run: uv build --python=python3.7
